### ISSUE TITLE
API body does not have the necessary parameter: model_artifact_location .

### ISSUE THREAD

**Issue by AditModi** [awslabs/aws-mlops-framework#1]
I tried to run the already available template using below link.
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?templateURL=https:%2F%2Fs3.amazonaws.com%2Fsolutions-reference%2Faws-mlops-framework%2Flatest%2Faws-mlops-framework.template

I am referring to below solution 
https://aws.amazon.com/solutions/implementations/aws-mlops-framework/?did=sl_card&trk=sl_card

Once I run the cloudformation stack , the creation is complete , I need to provision the pipeline using the given link, on clicking the link I get a missing authentication token.

once I provision the pipeline to a valid link , I get message: forbidden

I specify details as:

{
  "pipeline_type" : "byom",
  "custom_model_container": "custom/model.zip",
  "model_framework": "xgboost",
  "model_framework_version": "1",
  "model_name": "my-model-name",
  "training_data": "training_data/data.csv",
  "inference_instance": "ml.m5.large",
  "inference_type": "realtime | batch",
  "batch_inference_data": "batch_inference/data.csv"
}

What mistakes am I making? how to correct them ??

Solved both message: forbidden and missing authentication issue.

now when I try running it , I get

{"message": "Bad request. API body does not have the necessary parameter: model_artifact_location"}

what should I specify as model_artifact_location ???

**Comment by AditModi** [comment]
AWS MLOps Framework provisions a pipeline based on the inputs received from either an API call or a Git repository. 
I would like to use a sample model to understand the working of project. How can I do it??
What should I be specifying in the codecommit repo ??
what files should my model contain?? ( I am aware it requires dockerfile and files for building Amazon SageMaker compatible Docker image but I need to know specifically what all files and if preferrable an example would be helpful )
Further more if there is any documentation on what all to upload and where to upload it could be helpful.

**Comment by tabdunabi** [comment]
Hi @AditModi, thank you for trying our solution. 
The API call body, in the example you provided is missing `"model_artifact_location"`. For example, here is the API body to provision a `Sagemaker Inference Endpoint` using `Sagemaker Builtin algorithms` (e.g. `linear-learner`):
```
{
    "pipeline_type": "byom",
    "custom_model_container": "",
    "model_framework": "linear-learner",
    "model_framework_version": "1",
    "model_name": "myrealtimemodel",
    "model_artifact_location": "model.tar.gz",
    "training_data": "training/data.csv",
    "inference_instance": "ml.m5.large",
    "inference_type": "realtime",
    "batch_inference_data": ""
}
```
In this example, you need to upload your trained model (e.g. using `linear-learner` builtin algorithm) to the root of the `assets S3 bucket` created by the pipeline. A link to the assets S3 bucket can be found in the outputs of the Cloud formation template.  
Notice here the `"custom_model_container": ""` is left empty because we are using `Sagemaker Builtin algorithm`.

A second example to provision a `Sagemaker Inference Endpoint` using `your own custom algorithm` :
```
{
   "pipeline_type": "byom",
	"custom_model_container": "custom/custom_image.zip",
	"model_framework": "",
	"model_framework_version": "",
	"model_name": "mycustomrealtimemodel",
	"model_artifact_location": "model.tar.gz",
	"training_data": "training/my_data.csv",
	"inference_instance": "ml.m5.large",
	"inference_type": "realtime",
	"batch_inference_data": ""
}
```
Here the `"custom_model_container": "custom/custom_image.zip"` is specified, which refers to the location of your `custom algorithm docker image assets` (as required by `Sagemaker`) in the `assets S3 bucket`. The `"model_framework": ""` and `"model_framework_version": ""` are left empty because we are using custom algorithm.

**Comment by AditModi** [comment]
hi @tabdunabi ,
you mentioned "you need to upload your trained model (e.g. using linear-learner builtin algorithm) to the root of the assets S3 bucket created by the pipeline. " I am unclear as to what should my training model (e.g. using linear-learner builtin algorithm) contain ( what are the different files the trained model should comprise of ) . what is the file structure that is being stored to the root of the assets s3 bucket. 
Giving an example of the trained model that i can upload to assets s3 bucket could be really helpful.

Also regarding the custom algorithm, the custom_model_container refers to the location of your custom algorithm docker image assets (as required by Sagemaker) in the assets S3 bucket. ( is it possible to list all the files that the zip file is expected to have ie dockerfile etc )
It could be really helpful if you could provide a sample zip containing all the necessary files ( as a sample example to refer to ) and file structure in which the model is zipped and uploaded to s3 bucket.

**Comment by tabdunabi** [comment]
@AditModi , the solution uses models trained using Sagemaker. you should know how to develop ML models using Sagemaker. Please see [Sagemaker developer guide](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-dg.pdf) and [examples](https://github.com/aws/amazon-sagemaker-examples). When using Sagemaker, the trained model is saved in `*.tar.gz` format. 

Regarding what should the custom container `zip` file include, please see examples provided in this [page](https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers-notebooks.html). Follow the links for the different examples to see detailed notebooks.

**Comment by AditModi** [comment]
@tabdunabi ,
I trained a model using amazon sagemaker and using the api call provisioned the pipeline . the pipeline would fetch the artifacts I created earlier. everything works for a model trained using sagemaker.
Currently I have a different use-case. I would like to build/train a model ( elsewhere not aws sagemaker) and deploy model using the provision pipeline feature. Do I require to use the custom container ( bring your own model feature ) if so, then how to achieve that.
I saw the  [bring your own model example using scikit-learn](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own) example but I am still unable to grasp what all should the zip file include . take an example say the [scikit_learn_bring_your_own_model](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own) should contain the zip of the container folder ???

**Comment by tabdunabi** [comment]
Hi @AditModi,  
Currently, the solution supports models trained using [Amazon SageMaker builtin algorithms](https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html), or Bring Your Own Model (BYOM) feature via a custom docker image, and supporting files,  that is compatible with Amazon SageMaker Endpoint. 
In the example [bring your own model example using scikit-learn](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own), the `custom/custom_image.zip` in `"custom_model_container": "custom_image.zip"` should contain the contents of the [container folder](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own/container).

**Comment by AditModi** [comment]
In the example bring your own model example using scikit-learn, the custom/custom_image.zip in "custom_model_container": "custom_image.zip" should contain the contents of the container folder. I followed the same approach as mentioned by you.
Issues faced:
the Code-Deploy step fails.
In the cloudwatch logs it is mentioned that An error occurred (ValidationException) when calling the DescribeModel operation: Could not find model "arn:aws:sagemaker:us-east-1:account-arn:model/decision-tree-model".
What is causing this issue?? 

A second example to provision a Sagemaker Inference Endpoint using your own custom algorithm :

{
      "pipeline_type": "byom",
      "custom_model_container": "custom/custom_image.zip",
      "model_framework": "",
      "model_framework_version": "",
      "model_name": "mycustomrealtimemodel",
      "model_artifact_location": "model.tar.gz",
      "training_data": "training/my_data.csv",
      "inference_instance": "ml.m5.large",
      "inference_type": "realtime",
      "batch_inference_data": ""
}
Here the "custom_model_container": "custom/custom_image.zip" is specified, which refers to the location of your custom algorithm docker image assets (as required by Sagemaker) in the assets S3 bucket. The "model_framework": "" and "model_framework_version": "" are left empty because we are using custom algorithm.

I am specifying the provision pipeline as shown earlier. 
How to ensure that a sample-application work for our use-case.

**Comment by tabdunabi** [comment]
Hi @AditModi , there is an issue with the mentioned SageMaker example. If look at this [issue](https://github.com/aws/amazon-sagemaker-examples/issues/1953) I created yesterday, you will find the easy fix for the Dockerfile. 
Please apply the same fix in your Dockerfile, re-zip the folder, upload again to S3, and retry. 
Note: when zipping the custom_image folder use something like the following.
```
cd custome_image
zip -r ../custom_image.zip *
```

**Comment by aassadza** [comment]
Hi @AditModi, following up on this issue that you mentioned on SageMaker example, the [amazon-sagemaker-examples issue](https://github.com/aws/amazon-sagemaker-examples/pull/1971) was addressed and merged on Feb 16.

Thank you for your inquiry. Please let us know if you need additional assistance here. Closing this issue for now.
